added create LB from GHA

diff --git a/.github/workflows/terr_rm.yaml b/.github/workflows/terr_rm.yaml
--- a/.github/workflows/terr_rm.yaml
+++ b/.github/workflows/terr_rm.yaml
@@ -1070,233 +1070,227 @@ jobs:
           path: rm_outputs.json
 
 
-#   create_web_oke_lb_service_and_tls:
-#     name: Create WEB OKE LoadBalancer Service
-#     runs-on: ubuntu-latest
-#     needs: apply
+  create_stg_lb_service_and_tls:
+    name: Create OKE LoadBalancer Service
+    runs-on: ubuntu-latest
+    needs: apply
 
-#     env:
-#       OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
-#       OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
-#       OCI_REGION: ${{ secrets.OCI_REGION }}
-#       OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
-#       OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
-#       OCI_PRIVATE_KEY_PASSPHRASE: ${{ secrets.OCI_PRIVATE_KEY_PASSPHRASE }}
+    env:
+      OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
+      OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
+      OCI_REGION: ${{ secrets.OCI_REGION }}
+      OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
+      OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
+      OCI_PRIVATE_KEY_PASSPHRASE: ${{ secrets.OCI_PRIVATE_KEY_PASSPHRASE }}
 
-#     steps:
-#       - name: Download RM outputs artifact
-#         uses: actions/download-artifact@v8
-#         with:
-#           name: rm_outputs
+    steps:
+      - name: Download RM outputs artifact
+        uses: actions/download-artifact@v8
+        with:
+          name: rm_outputs
 
-#       - name: List download file
-#         run: | 
-#           pwd
-#           ls -al
+      - name: List download file
+        run: | 
+          pwd
+          ls -al
 
-#       - name: Parse RM outputs
-#         shell: bash
-#         run: |
-#           set -euo pipefail
+      - name: Parse RM outputs
+        shell: bash
+        run: |
+          set -euo pipefail
 
-#           BASTION_PUBLIC_IP=$(jq -r '.data.items[] | select(."output-name"=="bastion_public_ip") | ."output-value"' rm_outputs.json)
-#           WEB_OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="web_oke_cluster_ocid") | ."output-value"' rm_outputs.json)
-#           CMS_OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="cms_oke_cluster_ocid") | ."output-value"' rm_outputs.json)
-#           AIRS_OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="airs_oke_cluster_ocid") | ."output-value"' rm_outputs.json)
-#           LB_SUBNET_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_subnet_ocid") | ."output-value"' rm_outputs.json)
-#           LB_NSG_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_nsg_ocid") | ."output-value"' rm_outputs.json)
-#           WEB_LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="web_lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
-#           CMS_LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="cms_lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
-#           AIRS_LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="airs_lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
+          BASTION_PUBLIC_IP=$(jq -r '.data.items[] | select(."output-name"=="bastion_public_ip") | ."output-value"' rm_outputs.json)
+          STG_OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="airs_oke_cluster_ocid") | ."output-value"' rm_outputs.json)
+          LB_SUBNET_OCID=$(jq -r '.data.items[] | select(."output-name"=="stg_lb_subnet_ocid") | ."output-value"' rm_outputs.json)
+          LB_NSG_OCID=$(jq -r '.data.items[] | select(."output-name"=="stg_lb_nsg_ocid") | ."output-value"' rm_outputs.json)
+          LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="stg_lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
 
-#           for v in WEB_OKE_CLUSTER_OCID LB_SUBNET_OCID LB_NSG_OCID WEB_LB_RESERVED_PUBLIC_IP_OCID; do
-#             val="${!v:-}"
-#             if [ -z "${val}" ] || [ "${val}" = "null" ]; then
-#               echo "::error::${v} is empty or null"
-#               exit 1
-#             fi
-#           done
+          for v in STG_OKE_CLUSTER_OCID LB_SUBNET_OCID LB_NSG_OCID WEB_LB_RESERVED_PUBLIC_IP_OCID; do
+            val="${!v:-}"
+            if [ -z "${val}" ] || [ "${val}" = "null" ]; then
+              echo "::error::${v} is empty or null"
+              exit 1
+            fi
+          done
  
-#           echo "BASTION_PUBLIC_IP=${BASTION_PUBLIC_IP}" >> "$GITHUB_ENV"
-#           echo "WEB_OKE_CLUSTER_OCID=${WEB_OKE_CLUSTER_OCID}" >> "$GITHUB_ENV"
-#           echo "LB_SUBNET_OCID=${LB_SUBNET_OCID}" >> "$GITHUB_ENV"
-#           echo "LB_NSG_OCID=${LB_NSG_OCID}" >> "$GITHUB_ENV"
-#           echo "WEB_LB_RESERVED_PUBLIC_IP_OCID=${WEB_LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
-#           echo "CMS_LB_RESERVED_PUBLIC_IP_OCID=${CMS_LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
-#           echo "AIRS_LB_RESERVED_PUBLIC_IP_OCID=${AIRS_LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
+          echo "BASTION_PUBLIC_IP=${BASTION_PUBLIC_IP}" >> "$GITHUB_ENV"
+          echo "STG_OKE_CLUSTER_OCID=${WEB_OKE_CLUSTER_OCID}" >> "$GITHUB_ENV"
+          echo "LB_SUBNET_OCID=${LB_SUBNET_OCID}" >> "$GITHUB_ENV"
+          echo "LB_NSG_OCID=${LB_NSG_OCID}" >> "$GITHUB_ENV"
+          echo "LB_RESERVED_PUBLIC_IP_OCID=${AIRS_LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
 
 
-#       - name: Checkout repo
-#         uses: actions/checkout@v6
+      - name: Checkout repo
+        uses: actions/checkout@v6
 
-#       - name: Install OCI CLI
-#         run: |
-#           python3 -m pip install --upgrade pip
-#           python3 -m pip install oci-cli
+      - name: Install OCI CLI
+        run: |
+          python3 -m pip install --upgrade pip
+          python3 -m pip install oci-cli
 
-#       - name: Configure OCI CLI
-#         shell: bash
-#         run: |
-#           set -euo pipefail
+      - name: Configure OCI CLI
+        shell: bash
+        run: |
+          set -euo pipefail
 
-#           mkdir -p ~/.oci
-#           chmod 700 ~/.oci
+          mkdir -p ~/.oci
+          chmod 700 ~/.oci
 
-#           printf '%s\n' "${OCI_PRIVATE_KEY}" > ~/.oci/oci_api_key.pem
-#           chmod 600 ~/.oci/oci_api_key.pem
+          printf '%s\n' "${OCI_PRIVATE_KEY}" > ~/.oci/oci_api_key.pem
+          chmod 600 ~/.oci/oci_api_key.pem
 
-#           cat > ~/.oci/config <<EOF
-#           [DEFAULT]
-#           user=${OCI_USER_OCID}
-#           tenancy=${OCI_TENANCY_OCID}
-#           region=${OCI_REGION}
-#           fingerprint=${OCI_FINGERPRINT}
-#           pass_phrase=${OCI_PRIVATE_KEY_PASSPHRASE}
-#           key_file=${HOME}/.oci/oci_api_key.pem
-#           EOF
+          cat > ~/.oci/config <<EOF
+          [DEFAULT]
+          user=${OCI_USER_OCID}
+          tenancy=${OCI_TENANCY_OCID}
+          region=${OCI_REGION}
+          fingerprint=${OCI_FINGERPRINT}
+          pass_phrase=${OCI_PRIVATE_KEY_PASSPHRASE}
+          key_file=${HOME}/.oci/oci_api_key.pem
+          EOF
 
-#           chmod 600 ~/.oci/config
+          chmod 600 ~/.oci/config
 
-#       - name: Install kubectl
-#         uses: Azure/setup-kubectl@v5.1.0
-#         with:
-#           version: latest
+      - name: Install kubectl
+        uses: Azure/setup-kubectl@v5.1.0
+        with:
+          version: latest
     
-#       - name: Get OKE private API endpoint
-#         shell: bash
-#         run: |
-#           set -euo pipefail
+      - name: Get OKE private API endpoint
+        shell: bash
+        run: |
+          set -euo pipefail
 
-#           ENDPOINT=$(oci ce cluster get \
-#             --cluster-id "$WEB_OKE_CLUSTER_OCID" \
-#             --region "$OCI_REGION" \
-#             | jq -r '.data.endpoints."private-endpoint"')
+          ENDPOINT=$(oci ce cluster get \
+            --cluster-id "$STG_OKE_CLUSTER_OCID" \
+            --region "$OCI_REGION" \
+            | jq -r '.data.endpoints."private-endpoint"')
 
-#           if [[ -z "$ENDPOINT" || "$ENDPOINT" == "null" ]]; then
-#              echo "::error::Private endpoint not found"
-#              exit 1
-#           fi
+          if [[ -z "$ENDPOINT" || "$ENDPOINT" == "null" ]]; then
+             echo "::error::Private endpoint not found"
+             exit 1
+          fi
 
-#           # Example: https://10.0.1.6:6443
-#           HOSTPORT="${ENDPOINT#https://}"
-#           OKE_API_PRIVATE_IP="${HOSTPORT%%:*}"
-#           OKE_API_PRIVATE_PORT="${HOSTPORT##*:}"
+          # Example: https://10.0.1.6:6443
+          HOSTPORT="${ENDPOINT#https://}"
+          OKE_API_PRIVATE_IP="${HOSTPORT%%:*}"
+          OKE_API_PRIVATE_PORT="${HOSTPORT##*:}"
 
-#           echo "OKE_API_PRIVATE_IP=$OKE_API_PRIVATE_IP" >> $GITHUB_ENV
-#           echo "OKE_API_PRIVATE_PORT=$OKE_API_PRIVATE_PORT" >> $GITHUB_ENV
+          echo "OKE_API_PRIVATE_IP=$OKE_API_PRIVATE_IP" >> $GITHUB_ENV
+          echo "OKE_API_PRIVATE_PORT=$OKE_API_PRIVATE_PORT" >> $GITHUB_ENV
 
-#           echo "OKE private API: $OKE_API_PRIVATE_IP:$OKE_API_PRIVATE_PORT"
+          echo "OKE private API: $OKE_API_PRIVATE_IP:$OKE_API_PRIVATE_PORT"
       
-#       - name: Start SSH tunnel via bastion
-#         shell: bash
-#         env:
-#           BASTION_SSH_PRIVATE_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
-#           BASTION_USER: ${{ secrets.BASTION_USER }}
-#           OKE_API_PRIVATE_IP: ${{ env.OKE_API_PRIVATE_IP }}
-#           OKE_API_PRIVATE_PORT: ${{ env.OKE_API_PRIVATE_PORT }}
-#         run: |
-#          set -euo pipefail
+      - name: Start SSH tunnel via bastion
+        shell: bash
+        env:
+          BASTION_SSH_PRIVATE_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
+          BASTION_USER: ${{ secrets.BASTION_USER }}
+          OKE_API_PRIVATE_IP: ${{ env.OKE_API_PRIVATE_IP }}
+          OKE_API_PRIVATE_PORT: ${{ env.OKE_API_PRIVATE_PORT }}
+        run: |
+         set -euo pipefail
 
-#          mkdir -p ~/.ssh
-#          echo "$BASTION_SSH_PRIVATE_KEY" > ~/.ssh/bastion.pem
-#          chmod 600 ~/.ssh/bastion.pem
+         mkdir -p ~/.ssh
+         echo "$BASTION_SSH_PRIVATE_KEY" > ~/.ssh/bastion.pem
+         chmod 600 ~/.ssh/bastion.pem
 
-#          ssh -i ~/.ssh/bastion.pem \
-#            -o StrictHostKeyChecking=no \
-#            -o UserKnownHostsFile=/dev/null \
-#            -N \
-#            -L 6443:${OKE_API_PRIVATE_IP}:${OKE_API_PRIVATE_PORT} \
-#            ${BASTION_USER}@${BASTION_PUBLIC_IP} &
+         ssh -i ~/.ssh/bastion.pem \
+           -o StrictHostKeyChecking=no \
+           -o UserKnownHostsFile=/dev/null \
+           -N \
+           -L 6443:${OKE_API_PRIVATE_IP}:${OKE_API_PRIVATE_PORT} \
+           ${BASTION_USER}@${BASTION_PUBLIC_IP} &
 
 
-#       - name: Create kubeconfig for OKE
-#         shell: bash
-#         run: |
-#           set -euo pipefail
-#           mkdir -p "$HOME/.kube"
+      - name: Create kubeconfig for OKE
+        shell: bash
+        run: |
+          set -euo pipefail
+          mkdir -p "$HOME/.kube"
 
-#           oci ce cluster create-kubeconfig \
-#             --cluster-id "${WEB_OKE_CLUSTER_OCID}" \
-#             --file "$HOME/.kube/config" \
-#             --region "${OCI_REGION}" \
-#             --token-version 2.0.0 \
-#             --kube-endpoint PRIVATE_ENDPOINT \
-#             --overwrite
+          oci ce cluster create-kubeconfig \
+            --cluster-id "${STG_OKE_CLUSTER_OCID}" \
+            --file "$HOME/.kube/config" \
+            --region "${OCI_REGION}" \
+            --token-version 2.0.0 \
+            --kube-endpoint PRIVATE_ENDPOINT \
+            --overwrite
 
-#           # Update kubeconfig to use localhost (SSH tunnel endpoint)
-#           sed -i 's/https:\/\/[^:]\+:6443/https:\/\/127.0.0.1:6443/g' ~/.kube/config
-#           cat ~/.kube/config
+          # Update kubeconfig to use localhost (SSH tunnel endpoint)
+          sed -i 's/https:\/\/[^:]\+:6443/https:\/\/127.0.0.1:6443/g' ~/.kube/config
+          cat ~/.kube/config
 
-#           export KUBECONFIG="$HOME/.kube/config"
-#           kubectl get nodes
+          export KUBECONFIG="$HOME/.kube/config"
+          kubectl get nodes
 
-#       - name: Apply DevOps-managed Web Cluster LoadBalancer 
-#         shell: bash
-#         run: |
-#           set -euo pipefail
-#           export KUBECONFIG="$HOME/.kube/config"
+      - name: Apply DevOps-managed Web Cluster LoadBalancer 
+        shell: bash
+        run: |
+          set -euo pipefail
+          export KUBECONFIG="$HOME/.kube/config"
 
-#           cat <<EOF > oke-lb-service.yaml
-#           apiVersion: v1
-#           kind: Service
-#           metadata:
-#             name: web-lb
-#             namespace: default
-#             annotations:
-#               oci.oraclecloud.com/load-balancer-type: "lb"
-#               service.beta.kubernetes.io/oci-load-balancer-subnet1: "${LB_SUBNET_OCID}"
-#               oci.oraclecloud.com/oci-network-security-groups: "${LB_NSG_OCID}"
-#               service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
-#               service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
-#               service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
-#               service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "1000"
-#               # service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
-#               # oci.oraclecloud.com/oci-load-balancer-listener-ssl-config: '{"CipherSuiteName":"oci-tls-12-ssl-cipher-suite-v3", "Protocols":["TLSv1.2"]}'
-#               # service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
-#               # service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
-#           spec:
-#             loadBalancerIP: "${WEB_LB_RESERVED_PUBLIC_IP_OCID}"
-#             type: LoadBalancer
-#             selector:
-#               app: myapp
-#             ports:
-#               - name: http
-#                 port: 80
-#                 targetPort: 80
-#               - name: https
-#                 port: 443
-#                 targetPort: 80
-#             selector:
-#               app: cake
-#           EOF
+          cat <<EOF > oke-lb-service.yaml
+          apiVersion: v1
+          kind: Service
+          metadata:
+            name: web-lb
+            namespace: default
+            annotations:
+              oci.oraclecloud.com/load-balancer-type: "lb"
+              service.beta.kubernetes.io/oci-load-balancer-subnet1: "${LB_SUBNET_OCID}"
+              oci.oraclecloud.com/oci-network-security-groups: "${LB_NSG_OCID}"
+              service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
+              service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
+              service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
+              service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "1000"
+              # service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
+              # oci.oraclecloud.com/oci-load-balancer-listener-ssl-config: '{"CipherSuiteName":"oci-tls-12-ssl-cipher-suite-v3", "Protocols":["TLSv1.2"]}'
+              # service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
+              # service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
+          spec:
+            loadBalancerIP: "${LB_RESERVED_PUBLIC_IP_OCID}"
+            type: LoadBalancer
+            selector:
+              app: myapp
+            ports:
+              - name: http
+                port: 80
+                targetPort: 80
+              - name: https
+                port: 443
+                targetPort: 80
+            selector:
+              app: cake
+          EOF
 
-#           # kubectl create namespace platform-apps --dry-run=client -o yaml | kubectl apply -f -
-#           cat oke-lb-service.yaml
-#           kubectl apply -f oke-lb-service.yaml
-#           kubectl get svc web-lb -o wide
+          # kubectl create namespace platform-apps --dry-run=client -o yaml | kubectl apply -f -
+          cat oke-lb-service.yaml
+          kubectl apply -f oke-lb-service.yaml
+          kubectl get svc web-lb -o wide
 
-#       - name: Deploy TLS secret
-#         shell: bash
-#         env:
-#           TLSCRT: ${{ secrets.TLSCRT }}
-#           TLSKEY: ${{ secrets.TLSKEY }}
-#         run: |
-#           set -euo pipefail
-#           cat > secret.yaml <<EOF
-#           apiVersion: v1
-#           kind: Secret
-#           metadata:
-#             name: ssl-certificate-secret
-#           type: kubernetes.io/tls
-#           stringData:
-#             tls.crt: |
-#           $(printf '%s\n' "$TLSCRT" | sed 's/^/        /')
-#             tls.key: |
-#           $(printf '%s\n' "$TLSKEY" | sed 's/^/        /')
-#           EOF
+      - name: Deploy TLS secret
+        shell: bash
+        env:
+          TLSCRT: ${{ secrets.TLSCRT }}
+          TLSKEY: ${{ secrets.TLSKEY }}
+        run: |
+          set -euo pipefail
+          cat > secret.yaml <<EOF
+          apiVersion: v1
+          kind: Secret
+          metadata:
+            name: ssl-certificate-secret
+          type: kubernetes.io/tls
+          stringData:
+            tls.crt: |
+          $(printf '%s\n' "$TLSCRT" | sed 's/^/        /')
+            tls.key: |
+          $(printf '%s\n' "$TLSKEY" | sed 's/^/        /')
+          EOF
 
-#           # kubectl apply -f secret.yaml
-#           # kubectl get secret ssl-certificate-secret
+          # kubectl apply -f secret.yaml
+          # kubectl get secret ssl-certificate-secret
 
   
   # create_airs_oke_lb_service_and_tls:
